#
# This is free software, lisence use MIT.
# 
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
# 
# <https://github.com/KFERMercer/OpenWrt-CI>
# 

name: 编译LEDE

on:
  #schedule:
  #  - cron: 0 20 * * *
  push:
    tags:
    - 'v*'
    branches: 
      - master
  
jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
      - name: 查看版本
        uses: actions/checkout@master

      - name: 准备环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi `docker images -q`
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
          sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
          sudo -E apt-get update
          sudo -E apt-get -y install build-essential asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake libtool autopoint device-tree-compiler
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean

          # 利用挂载在 /mnt/ 的 14G 额外空间:
          # sudo mkdir -p -m 777 /mnt/openwrt/bin /mnt/openwrt/build_dir/host /mnt/openwrt/build_dir/hostpkg /mnt/openwrt/dl /mnt/openwrt/feeds /mnt/openwrt/staging_dir
          # ln -s /mnt/openwrt/bin ./bin
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/host ./build_dir/host
          # mkdir -p ./build_dir/host && ln -s /mnt/openwrt/build_dir/hostpkg ./build_dir/hostpkg
          # ln -s /mnt/openwrt/dl ./dl
          # ln -s /mnt/openwrt/feeds ./feeds
          # ln -s /mnt/openwrt/staging_dir ./staging_dir

          df -h
          
      - name: 下载最新的源码
        run: |
          git clone https://github.com/coolsnowwolf/lede
          cd lede
          
      - name: 更新feeds
        run: |
          echo "src-git lienol https://github.com/Lienol/openwrt-package" >>feeds.conf.default
          ./scripts/feeds clean
          ./scripts/feeds update -a
          rm -rf feeds/lienol/lienol/ipt2socks
          rm -rf feeds/lienol/lienol/shadowsocksr-libev
          rm -rf feeds/lienol/lienol/pdnsd-alt
          rm -rf feeds/lienol/package/verysync
          rm -rf feeds/lienol/lienol/luci-app-verysync
          rm -rf package/lean/kcptun
          rm -rf package/lean/trojan
          rm -rf package/lean/v2ray
          rm -rf package/lean/luci-app-kodexplorer
          rm -rf package/lean/luci-app-pppoe-relay
          rm -rf package/lean/luci-app-pptp-server
          rm -rf package/lean/luci-app-v2ray-server
          ./scripts/feeds install -a
          
      - name: 自定义配置
        run: |
          rm -f ./.config*
          touch ./.config

          #
          # ========================固件定制部分========================
          # 

          # 
          # 如果不对本区块做出任何编辑, 则生成默认配置固件. 
          # 

          # 以下为定制化固件选项和说明:
          #

          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          # 
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #

          # 
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          # 
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          # 

          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          
          # 关闭DEBUG调试
          CONFIG_KERNEL_DEBUG_FS=n
          CONFIG_KERNEL_DEBUG_KERNEL=n
          CONFIG_KERNEL_DEBUG_INFO=n
          CONFIG_PACKAGE_MAC80211_DEBUGFS=n
          CONFIG_OPENLDAP_DEBUG=n
          EOF

          # 固件压缩:
          cat >> .config <<EOF
          CONFIG_TARGET_IMAGES_GZIP=y
          EOF
          
          # 编译UEFI固件:
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          # EOF

          # IPv6支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_dnsmasq_full_dhcpv6=n
          CONFIG_PACKAGE_ipv6helper=n
          EOF

          # 多文件系统支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-fs-nfs=n
          CONFIG_PACKAGE_kmod-fs-nfs-common=n
          CONFIG_PACKAGE_kmod-fs-nfs-v3=n
          CONFIG_PACKAGE_kmod-fs-nfs-v4=n
          CONFIG_PACKAGE_kmod-fs-ntfs=n
          CONFIG_PACKAGE_kmod-fs-squashfs=n
          EOF

          # USB3.0支持:
          cat >> .config <<EOF
          CONFIG_PACKAGE_kmod-usb-ohci=n
          CONFIG_PACKAGE_kmod-usb-ohci-pci=n
          CONFIG_PACKAGE_kmod-usb2=n
          CONFIG_PACKAGE_kmod-usb2-pci=n
          CONFIG_PACKAGE_kmod-usb3=n
          EOF

          # 常用LuCI插件选择:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-app-passwall=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ipt2socks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_socks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_socks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Brook=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_kcptun=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_haproxy=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ChinaDNS_NG=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_pdnsd=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_dns2socks=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_v2ray-plugin=y
          CONFIG_PACKAGE_luci-app-passwall_INCLUDE_simple-obfs=y
          CONFIG_PACKAGE_luci-app-firewall=y
          CONFIG_PACKAGE_luci-app-flowoffload=y
          CONFIG_PACKAGE_luci-app-filetransfer=y
          CONFIG_DEFAULT_luci-app-accesscontrol=n
          CONFIG_DEFAULT_luci-app-adbyby-plus=y
          CONFIG_DEFAULT_luci-app-arpbind=y
          CONFIG_PACKAGE_luci-app-nlbwmon=y
          CONFIG_PACKAGE_luci-app-cpufreq=y
          CONFIG_PACKAGE_luci-app-autoreboot=y
          CONFIG_PACKAGE_luci-app-ramfree=y
          CONFIG_PACKAGE_luci-app-samba=y
          CONFIG_PACKAGE_luci-app-unblockmusic=y
          CONFIG_PACKAGE_luci-app-upnp=y
          CONFIG_PACKAGE_luci-app-wol=y
          CONFIG_DEFAULT_luci-app-vlmcsd=y
          #CONFIG_DEFAULT_luci-app-zerotier=y
          #CONFIG_DEFAULT_luci-app-vsftpd=y
          #CONFIG_DEFAULT_luci-app-ddns=y
          #CONFIG_DEFAULT_luci-app-sfe=y
          #CONFIG_DEFAULT_luci-app-sqm=y
          #CONFIG_DEFAULT_luci-app-ssr-plus=y
          EOF

          # LuCI主题:
          cat >> .config <<EOF
          CONFIG_PACKAGE_luci-theme-argon=y
          #CONFIG_PACKAGE_luci-theme-netgear=y
          EOF

          # 常用软件包:
          cat >> .config <<EOF
          CONFIG_PACKAGE_curl=n
          CONFIG_PACKAGE_htop=n
          CONFIG_PACKAGE_nano=n
          CONFIG_PACKAGE_screen=n
          CONFIG_PACKAGE_tree=n
          CONFIG_PACKAGE_vim-fuller=n
          CONFIG_PACKAGE_wget=n
          EOF
          
          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          # cat >> .config <<EOF
          # # CONFIG_TARGET_IMAGES_PAD is not set
          # # CONFIG_VMDK_IMAGES is not set
          # EOF

          # 
          # ========================固件定制部分结束========================
          # 

          sed -i 's/^[ \t]*//g' ./.config
          make defconfig
          
      - name: 下载依赖
        run: |
          make download -j8
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译固件
        run: |
          make -j$(nproc) || make -j1 V=s
          echo "======================="
          echo "Space usage:"
          echo "======================="
          df -h
          echo "======================="
          du -h --max-depth=1 ./ --exclude=build_dir --exclude=bin
          du -h --max-depth=1 ./build_dir
          du -h --max-depth=1 ./bin

      - name: 打包固件
        run: find ./bin/targets/ -type d -name "packages" | xargs rm -rf {}

      - name: 上传固件
        uses: actions/upload-artifact@master
        with:
          name: OpenWrt firmware
          path: ./bin/targets/
